package com.farmsense.service;

import com.farmsense.model.entity.DetectionReport;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class PdfReportService {

    private static final DeviceRgb FARM_GREEN = new DeviceRgb(45, 106, 79);
    private static final DeviceRgb LIGHT_GREEN = new DeviceRgb(82, 183, 136);
    private static final DeviceRgb DARK_BG = new DeviceRgb(240, 248, 245);

    public byte[] generateReport(DetectionReport report) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        try (PdfDocument pdf = new PdfDocument(new PdfWriter(baos));
             Document doc = new Document(pdf)) {

            String date = report.getCreatedAt() != null
                    ? report.getCreatedAt().format(DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm"))
                    : "Unknown";

            // ── Header ──
            doc.add(new Paragraph("🌿 FarmSense AI")
                    .setFontSize(24).setBold()
                    .setFontColor(FARM_GREEN)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(2));
            doc.add(new Paragraph("Crop Disease Report")
                    .setFontSize(14)
                    .setFontColor(LIGHT_GREEN)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20));

            // ── Report Info Table ──
            Table infoTable = new Table(UnitValue.createPercentArray(new float[]{30, 70}))
                    .useAllAvailableWidth()
                    .setMarginBottom(15);

            addInfoRow(infoTable, "Report ID", report.getId());
            addInfoRow(infoTable, "Date", date);
            addInfoRow(infoTable, "Crop", safe(report.getCropName()));
            addInfoRow(infoTable, "Disease", safe(report.getDiseaseName()));
            addInfoRow(infoTable, "Confidence", report.getConfidence() != null ? report.getConfidence() + "%" : "N/A");
            addInfoRow(infoTable, "Severity", safe(report.getSeverity()));
            addInfoRow(infoTable, "Yield Loss Est.", safe(report.getYieldLossEstimate()));
            addInfoRow(infoTable, "Recovery Cost", safe(report.getEstimatedRecoveryCost()));
            doc.add(infoTable);

            // ── Sections ──
            addSection(doc, "🌱 Organic Treatment", safe(report.getOrganicTreatment()));
            addSection(doc, "💊 Chemical Treatment", safe(report.getChemicalTreatment()));
            addSection(doc, "🛡️ Preventive Measures", safe(report.getPreventiveMeasures()));
            addSection(doc, "⏰ Best Time to Treat", safe(report.getBestTimeToTreat()));

            // ── Footer ──
            doc.add(new Paragraph("\n"));
            doc.add(new Paragraph("Generated by FarmSense AI | " + date)
                    .setFontSize(8)
                    .setFontColor(ColorConstants.GRAY)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(20));
            doc.add(new Paragraph("https://farmsense.ai — AI-powered crop disease detection")
                    .setFontSize(7)
                    .setFontColor(ColorConstants.LIGHT_GRAY)
                    .setTextAlignment(TextAlignment.CENTER));
        }

        return baos.toByteArray();
    }

    private void addInfoRow(Table table, String label, String value) {
        table.addCell(new Cell()
                .add(new Paragraph(label).setFontSize(10).setBold().setFontColor(FARM_GREEN))
                .setBackgroundColor(DARK_BG)
                .setBorder(null)
                .setPadding(6));
        table.addCell(new Cell()
                .add(new Paragraph(safe(value)).setFontSize(10))
                .setBorder(null)
                .setPadding(6));
    }

    private void addSection(Document doc, String title, String content) {
        doc.add(new Paragraph(title)
                .setFontSize(12).setBold()
                .setFontColor(FARM_GREEN)
                .setMarginTop(12)
                .setMarginBottom(4));
        doc.add(new Paragraph(content)
                .setFontSize(10)
                .setFontColor(ColorConstants.DARK_GRAY)
                .setMarginBottom(8));
    }

    private String safe(String val) {
        return val != null && !val.isBlank() ? val : "N/A";
    }
}
